name: CI/CD

# main, deploy 브랜치에 push하면 워크플로우 실행
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      #  repository secrets에 올린 application.properties을 빌드 시 생성
      - name: Make application.properties
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.APPLICATION }}" > ./application.properties

      - name: Build with Gradle
        run: |
          chmod +x gradlew 
          ./gradlew build -x test

      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }} . 
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
            sudo docker rm -f $(sudo docker ps -aq) # 모든 컨테이너를 강제로 제거
            sudo docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
            cd ~
            sudo docker-compose up -d
            sudo docker image prune -f
